# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'RDM_DMX_Master.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QLabel, QLineEdit, QListWidget, QListWidgetItem,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSlider, QSpinBox, QStatusBar,
    QTabWidget, QWidget)
import resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(580, 697)
        self.actionDMX = QAction(MainWindow)
        self.actionDMX.setObjectName(u"actionDMX")
        self.actionRDM = QAction(MainWindow)
        self.actionRDM.setObjectName(u"actionRDM")
        self.actionReload = QAction(MainWindow)
        self.actionReload.setObjectName(u"actionReload")
        icon = QIcon()
        icon.addFile(u":/newPrefix/images/reload.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionReload.setIcon(icon)
        self.actionReload.setMenuRole(QAction.NoRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 20, 581, 646))
        palette = QPalette()
        brush = QBrush(QColor(225, 225, 225, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        self.tabWidget.setPalette(palette)
        font = QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet(u"tabWidget {\n"
"    background-color: rgb(232, 232, 232);\n"
"}")
        self.RDM_tab = QWidget()
        self.RDM_tab.setObjectName(u"RDM_tab")
        self.label_9 = QLabel(self.RDM_tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(225, 490, 111, 20))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.label_9.setFont(font1)
        self.label_9.setWordWrap(False)
        self.label_3 = QLabel(self.RDM_tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(100, 70, 61, 20))
        self.label_3.setFont(font1)
        self.label_2 = QLabel(self.RDM_tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(330, 50, 61, 16))
        self.label_10 = QLabel(self.RDM_tab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(130, 120, 20, 21))
        self.label_4 = QLabel(self.RDM_tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(220, 10, 141, 41))
        font2 = QFont()
        font2.setPointSize(16)
        font2.setBold(True)
        self.label_4.setFont(font2)
        self.label_11 = QLabel(self.RDM_tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(380, 120, 20, 20))
        self.source_UID = QLineEdit(self.RDM_tab)
        self.source_UID.setObjectName(u"source_UID")
        self.source_UID.setGeometry(QRect(400, 120, 121, 21))
        self.source_UID.setFrame(True)
        self.UID_label = QLabel(self.RDM_tab)
        self.UID_label.setObjectName(u"UID_label")
        self.UID_label.setGeometry(QRect(30, 120, 91, 20))
        self.UID_label.setFont(font1)
        self.parametro = QComboBox(self.RDM_tab)
        self.parametro.addItem("")
        self.parametro.addItem("")
        self.parametro.addItem("")
        self.parametro.setObjectName(u"parametro")
        self.parametro.setGeometry(QRect(250, 70, 221, 22))
        self.UID_S_Label = QLabel(self.RDM_tab)
        self.UID_S_Label.setObjectName(u"UID_S_Label")
        self.UID_S_Label.setGeometry(QRect(290, 120, 81, 20))
        self.UID_S_Label.setFont(font1)
        self.port_ID = QLineEdit(self.RDM_tab)
        self.port_ID.setObjectName(u"port_ID")
        self.port_ID.setGeometry(QRect(150, 160, 121, 21))
        self.port_ID.setMaxLength(32767)
        self.port_ID.setFrame(True)
        self.Subdevice_label = QLabel(self.RDM_tab)
        self.Subdevice_label.setObjectName(u"Subdevice_label")
        self.Subdevice_label.setGeometry(QRect(300, 160, 71, 20))
        self.Subdevice_label.setFont(font1)
        self.label_13 = QLabel(self.RDM_tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(130, 160, 20, 21))
        self.classe = QComboBox(self.RDM_tab)
        self.classe.addItem("")
        self.classe.addItem("")
        self.classe.addItem("")
        self.classe.setObjectName(u"classe")
        self.classe.setGeometry(QRect(170, 70, 68, 22))
        self.label = QLabel(self.RDM_tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(190, 50, 49, 16))
        self.send_command = QPushButton(self.RDM_tab)
        self.send_command.setObjectName(u"send_command")
        self.send_command.setGeometry(QRect(230, 445, 106, 31))
        self.Portid_label = QLabel(self.RDM_tab)
        self.Portid_label.setObjectName(u"Portid_label")
        self.Portid_label.setGeometry(QRect(70, 160, 51, 20))
        self.Portid_label.setFont(font1)
        self.destination_UID = QLineEdit(self.RDM_tab)
        self.destination_UID.setObjectName(u"destination_UID")
        self.destination_UID.setGeometry(QRect(150, 120, 121, 21))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.destination_UID.sizePolicy().hasHeightForWidth())
        self.destination_UID.setSizePolicy(sizePolicy)
        self.destination_UID.setBaseSize(QSize(0, 0))
        self.destination_UID.setFrame(True)
        self.sub_device = QLineEdit(self.RDM_tab)
        self.sub_device.setObjectName(u"sub_device")
        self.sub_device.setEnabled(False)
        self.sub_device.setGeometry(QRect(400, 160, 121, 21))
        self.sub_device.setFrame(True)
        self.sub_device.setDragEnabled(False)
        self.command_1 = QLineEdit(self.RDM_tab)
        self.command_1.setObjectName(u"command_1")
        self.command_1.setGeometry(QRect(20, 330, 22, 28))
        font3 = QFont()
        font3.setPointSize(10)
        self.command_1.setFont(font3)
        self.command_1.setLayoutDirection(Qt.LeftToRight)
        self.command_1.setReadOnly(True)
        self.command_2 = QLineEdit(self.RDM_tab)
        self.command_2.setObjectName(u"command_2")
        self.command_2.setGeometry(QRect(47, 330, 22, 28))
        self.command_2.setFont(font3)
        self.command_2.setLayoutDirection(Qt.LeftToRight)
        self.command_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_2.setReadOnly(True)
        self.command_4 = QLineEdit(self.RDM_tab)
        self.command_4.setObjectName(u"command_4")
        self.command_4.setGeometry(QRect(101, 330, 22, 28))
        self.command_4.setFont(font3)
        self.command_4.setLayoutDirection(Qt.LeftToRight)
        self.command_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_4.setReadOnly(True)
        self.command_3 = QLineEdit(self.RDM_tab)
        self.command_3.setObjectName(u"command_3")
        self.command_3.setGeometry(QRect(74, 330, 22, 28))
        self.command_3.setFont(font3)
        self.command_3.setLayoutDirection(Qt.LeftToRight)
        self.command_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_3.setReadOnly(True)
        self.command_6 = QLineEdit(self.RDM_tab)
        self.command_6.setObjectName(u"command_6")
        self.command_6.setGeometry(QRect(154, 330, 22, 28))
        self.command_6.setFont(font3)
        self.command_6.setLayoutDirection(Qt.LeftToRight)
        self.command_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_6.setReadOnly(True)
        self.command_8 = QLineEdit(self.RDM_tab)
        self.command_8.setObjectName(u"command_8")
        self.command_8.setGeometry(QRect(208, 330, 22, 28))
        self.command_8.setFont(font3)
        self.command_8.setLayoutDirection(Qt.LeftToRight)
        self.command_8.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_8.setReadOnly(True)
        self.command_7 = QLineEdit(self.RDM_tab)
        self.command_7.setObjectName(u"command_7")
        self.command_7.setGeometry(QRect(181, 330, 22, 28))
        self.command_7.setFont(font3)
        self.command_7.setLayoutDirection(Qt.LeftToRight)
        self.command_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_7.setReadOnly(True)
        self.command_5 = QLineEdit(self.RDM_tab)
        self.command_5.setObjectName(u"command_5")
        self.command_5.setGeometry(QRect(128, 330, 21, 28))
        self.command_5.setFont(font3)
        self.command_5.setLayoutDirection(Qt.LeftToRight)
        self.command_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_5.setReadOnly(True)
        self.command_14 = QLineEdit(self.RDM_tab)
        self.command_14.setObjectName(u"command_14")
        self.command_14.setGeometry(QRect(369, 330, 22, 28))
        self.command_14.setFont(font3)
        self.command_14.setLayoutDirection(Qt.LeftToRight)
        self.command_14.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_14.setReadOnly(True)
        self.command_10 = QLineEdit(self.RDM_tab)
        self.command_10.setObjectName(u"command_10")
        self.command_10.setGeometry(QRect(262, 330, 21, 28))
        self.command_10.setFont(font3)
        self.command_10.setLayoutDirection(Qt.LeftToRight)
        self.command_10.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_10.setReadOnly(True)
        self.command_16 = QLineEdit(self.RDM_tab)
        self.command_16.setObjectName(u"command_16")
        self.command_16.setGeometry(QRect(422, 330, 22, 28))
        self.command_16.setFont(font3)
        self.command_16.setLayoutDirection(Qt.LeftToRight)
        self.command_16.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_16.setReadOnly(True)
        self.command_12 = QLineEdit(self.RDM_tab)
        self.command_12.setObjectName(u"command_12")
        self.command_12.setGeometry(QRect(315, 330, 22, 28))
        self.command_12.setFont(font3)
        self.command_12.setLayoutDirection(Qt.LeftToRight)
        self.command_12.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_12.setReadOnly(True)
        self.command_15 = QLineEdit(self.RDM_tab)
        self.command_15.setObjectName(u"command_15")
        self.command_15.setGeometry(QRect(396, 330, 21, 28))
        self.command_15.setFont(font3)
        self.command_15.setLayoutDirection(Qt.LeftToRight)
        self.command_15.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_15.setReadOnly(True)
        self.command_11 = QLineEdit(self.RDM_tab)
        self.command_11.setObjectName(u"command_11")
        self.command_11.setGeometry(QRect(288, 330, 22, 28))
        self.command_11.setFont(font3)
        self.command_11.setLayoutDirection(Qt.LeftToRight)
        self.command_11.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_11.setReadOnly(True)
        self.command_13 = QLineEdit(self.RDM_tab)
        self.command_13.setObjectName(u"command_13")
        self.command_13.setGeometry(QRect(342, 330, 22, 28))
        self.command_13.setFont(font3)
        self.command_13.setLayoutDirection(Qt.LeftToRight)
        self.command_13.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_13.setReadOnly(True)
        self.command_9 = QLineEdit(self.RDM_tab)
        self.command_9.setObjectName(u"command_9")
        self.command_9.setGeometry(QRect(235, 330, 22, 28))
        self.command_9.setFont(font3)
        self.command_9.setLayoutDirection(Qt.LeftToRight)
        self.command_9.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_9.setReadOnly(True)
        self.command_20 = QLineEdit(self.RDM_tab)
        self.command_20.setObjectName(u"command_20")
        self.command_20.setGeometry(QRect(530, 330, 21, 28))
        self.command_20.setFont(font3)
        self.command_20.setLayoutDirection(Qt.LeftToRight)
        self.command_20.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_20.setReadOnly(True)
        self.command_18 = QLineEdit(self.RDM_tab)
        self.command_18.setObjectName(u"command_18")
        self.command_18.setGeometry(QRect(476, 330, 22, 28))
        self.command_18.setFont(font3)
        self.command_18.setLayoutDirection(Qt.LeftToRight)
        self.command_18.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_18.setReadOnly(True)
        self.command_19 = QLineEdit(self.RDM_tab)
        self.command_19.setObjectName(u"command_19")
        self.command_19.setGeometry(QRect(503, 330, 22, 28))
        self.command_19.setFont(font3)
        self.command_19.setLayoutDirection(Qt.LeftToRight)
        self.command_19.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_19.setReadOnly(True)
        self.command_17 = QLineEdit(self.RDM_tab)
        self.command_17.setObjectName(u"command_17")
        self.command_17.setGeometry(QRect(449, 330, 22, 28))
        self.command_17.setFont(font3)
        self.command_17.setLayoutDirection(Qt.LeftToRight)
        self.command_17.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_17.setReadOnly(True)
        self.command_26 = QLineEdit(self.RDM_tab)
        self.command_26.setObjectName(u"command_26")
        self.command_26.setGeometry(QRect(154, 380, 22, 28))
        self.command_26.setFont(font3)
        self.command_26.setLayoutDirection(Qt.LeftToRight)
        self.command_26.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_26.setReadOnly(True)
        self.command_31 = QLineEdit(self.RDM_tab)
        self.command_31.setObjectName(u"command_31")
        self.command_31.setGeometry(QRect(288, 380, 22, 28))
        self.command_31.setFont(font3)
        self.command_31.setLayoutDirection(Qt.LeftToRight)
        self.command_31.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_31.setReadOnly(True)
        self.command_32 = QLineEdit(self.RDM_tab)
        self.command_32.setObjectName(u"command_32")
        self.command_32.setGeometry(QRect(315, 380, 22, 28))
        self.command_32.setFont(font3)
        self.command_32.setLayoutDirection(Qt.LeftToRight)
        self.command_32.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_32.setReadOnly(True)
        self.command_29 = QLineEdit(self.RDM_tab)
        self.command_29.setObjectName(u"command_29")
        self.command_29.setGeometry(QRect(235, 380, 22, 28))
        self.command_29.setFont(font3)
        self.command_29.setLayoutDirection(Qt.LeftToRight)
        self.command_29.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_29.setReadOnly(True)
        self.command_37 = QLineEdit(self.RDM_tab)
        self.command_37.setObjectName(u"command_37")
        self.command_37.setGeometry(QRect(449, 380, 22, 28))
        self.command_37.setFont(font3)
        self.command_37.setLayoutDirection(Qt.LeftToRight)
        self.command_37.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_37.setReadOnly(True)
        self.command_30 = QLineEdit(self.RDM_tab)
        self.command_30.setObjectName(u"command_30")
        self.command_30.setGeometry(QRect(262, 380, 21, 28))
        self.command_30.setFont(font3)
        self.command_30.setLayoutDirection(Qt.LeftToRight)
        self.command_30.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_30.setReadOnly(True)
        self.command_22 = QLineEdit(self.RDM_tab)
        self.command_22.setObjectName(u"command_22")
        self.command_22.setGeometry(QRect(47, 380, 22, 28))
        self.command_22.setFont(font3)
        self.command_22.setLayoutDirection(Qt.LeftToRight)
        self.command_22.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_22.setReadOnly(True)
        self.command_36 = QLineEdit(self.RDM_tab)
        self.command_36.setObjectName(u"command_36")
        self.command_36.setGeometry(QRect(422, 380, 22, 28))
        self.command_36.setFont(font3)
        self.command_36.setLayoutDirection(Qt.LeftToRight)
        self.command_36.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_36.setReadOnly(True)
        self.command_28 = QLineEdit(self.RDM_tab)
        self.command_28.setObjectName(u"command_28")
        self.command_28.setGeometry(QRect(208, 380, 22, 28))
        self.command_28.setFont(font3)
        self.command_28.setLayoutDirection(Qt.LeftToRight)
        self.command_28.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_28.setReadOnly(True)
        self.command_24 = QLineEdit(self.RDM_tab)
        self.command_24.setObjectName(u"command_24")
        self.command_24.setGeometry(QRect(101, 380, 22, 28))
        self.command_24.setFont(font3)
        self.command_24.setLayoutDirection(Qt.LeftToRight)
        self.command_24.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_24.setReadOnly(True)
        self.command_27 = QLineEdit(self.RDM_tab)
        self.command_27.setObjectName(u"command_27")
        self.command_27.setGeometry(QRect(181, 380, 22, 28))
        self.command_27.setFont(font3)
        self.command_27.setLayoutDirection(Qt.LeftToRight)
        self.command_27.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_27.setReadOnly(True)
        self.command_23 = QLineEdit(self.RDM_tab)
        self.command_23.setObjectName(u"command_23")
        self.command_23.setGeometry(QRect(74, 380, 22, 28))
        self.command_23.setFont(font3)
        self.command_23.setLayoutDirection(Qt.LeftToRight)
        self.command_23.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_23.setReadOnly(True)
        self.command_25 = QLineEdit(self.RDM_tab)
        self.command_25.setObjectName(u"command_25")
        self.command_25.setGeometry(QRect(128, 380, 21, 28))
        self.command_25.setFont(font3)
        self.command_25.setLayoutDirection(Qt.LeftToRight)
        self.command_25.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_25.setReadOnly(True)
        self.command_21 = QLineEdit(self.RDM_tab)
        self.command_21.setObjectName(u"command_21")
        self.command_21.setGeometry(QRect(20, 380, 22, 28))
        self.command_21.setFont(font3)
        self.command_21.setLayoutDirection(Qt.LeftToRight)
        self.command_21.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_21.setReadOnly(True)
        self.command_34 = QLineEdit(self.RDM_tab)
        self.command_34.setObjectName(u"command_34")
        self.command_34.setGeometry(QRect(369, 380, 22, 28))
        self.command_34.setFont(font3)
        self.command_34.setLayoutDirection(Qt.LeftToRight)
        self.command_34.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_34.setReadOnly(True)
        self.command_33 = QLineEdit(self.RDM_tab)
        self.command_33.setObjectName(u"command_33")
        self.command_33.setGeometry(QRect(342, 380, 22, 28))
        self.command_33.setFont(font3)
        self.command_33.setLayoutDirection(Qt.LeftToRight)
        self.command_33.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_33.setReadOnly(True)
        self.command_35 = QLineEdit(self.RDM_tab)
        self.command_35.setObjectName(u"command_35")
        self.command_35.setGeometry(QRect(396, 380, 21, 28))
        self.command_35.setFont(font3)
        self.command_35.setLayoutDirection(Qt.LeftToRight)
        self.command_35.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_35.setReadOnly(True)
        self.label_20 = QLabel(self.RDM_tab)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(140, 300, 296, 20))
        self.command_38 = QLineEdit(self.RDM_tab)
        self.command_38.setObjectName(u"command_38")
        self.command_38.setGeometry(QRect(476, 380, 22, 28))
        self.command_38.setFont(font3)
        self.command_38.setLayoutDirection(Qt.LeftToRight)
        self.command_38.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_38.setReadOnly(True)
        self.command_40 = QLineEdit(self.RDM_tab)
        self.command_40.setObjectName(u"command_40")
        self.command_40.setGeometry(QRect(530, 380, 21, 28))
        self.command_40.setFont(font3)
        self.command_40.setLayoutDirection(Qt.LeftToRight)
        self.command_40.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_40.setReadOnly(True)
        self.command_39 = QLineEdit(self.RDM_tab)
        self.command_39.setObjectName(u"command_39")
        self.command_39.setGeometry(QRect(503, 380, 22, 28))
        self.command_39.setFont(font3)
        self.command_39.setLayoutDirection(Qt.LeftToRight)
        self.command_39.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_39.setReadOnly(True)
        self.add_param_1 = QLineEdit(self.RDM_tab)
        self.add_param_1.setObjectName(u"add_param_1")
        self.add_param_1.setEnabled(False)
        self.add_param_1.setGeometry(QRect(150, 200, 121, 21))
        self.add_param_1.setMaxLength(32767)
        self.add_param_1.setFrame(True)
        self.add_param_1_label = QLabel(self.RDM_tab)
        self.add_param_1_label.setObjectName(u"add_param_1_label")
        self.add_param_1_label.setEnabled(True)
        self.add_param_1_label.setGeometry(QRect(0, 200, 121, 20))
        self.add_param_1_label.setFont(font1)
        self.label_63 = QLabel(self.RDM_tab)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setEnabled(True)
        self.label_63.setGeometry(QRect(130, 200, 20, 21))
        self.label_64 = QLabel(self.RDM_tab)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setEnabled(True)
        self.label_64.setGeometry(QRect(380, 200, 20, 20))
        self.add_param_2 = QLineEdit(self.RDM_tab)
        self.add_param_2.setObjectName(u"add_param_2")
        self.add_param_2.setEnabled(False)
        self.add_param_2.setGeometry(QRect(400, 200, 121, 21))
        self.add_param_2.setMaxLength(32767)
        self.add_param_2.setFrame(True)
        self.add_param_2_label = QLabel(self.RDM_tab)
        self.add_param_2_label.setObjectName(u"add_param_2_label")
        self.add_param_2_label.setEnabled(True)
        self.add_param_2_label.setGeometry(QRect(310, 200, 61, 20))
        self.add_param_2_label.setFont(font1)
        self.frame_size = QLineEdit(self.RDM_tab)
        self.frame_size.setObjectName(u"frame_size")
        self.frame_size.setGeometry(QRect(312, 260, 61, 21))
        self.frame_size.setMaxLength(32767)
        self.frame_size.setFrame(True)
        self.label_5 = QLabel(self.RDM_tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(190, 260, 111, 20))
        self.label_59 = QLabel(self.RDM_tab)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(380, 160, 20, 20))
        self.label_22 = QLabel(self.RDM_tab)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(48, 360, 21, 16))
        self.label_21 = QLabel(self.RDM_tab)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 360, 21, 16))
        self.label_23 = QLabel(self.RDM_tab)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(75, 360, 21, 16))
        self.label_26 = QLabel(self.RDM_tab)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(101, 360, 21, 16))
        self.label_25 = QLabel(self.RDM_tab)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(155, 360, 16, 16))
        self.label_24 = QLabel(self.RDM_tab)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(128, 360, 21, 16))
        self.label_29 = QLabel(self.RDM_tab)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(182, 360, 21, 16))
        self.label_27 = QLabel(self.RDM_tab)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(209, 360, 21, 16))
        self.label_28 = QLabel(self.RDM_tab)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(235, 360, 21, 16))
        self.label_35 = QLabel(self.RDM_tab)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(262, 360, 21, 16))
        self.label_30 = QLabel(self.RDM_tab)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(289, 360, 21, 16))
        self.label_31 = QLabel(self.RDM_tab)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(316, 360, 21, 16))
        self.label_38 = QLabel(self.RDM_tab)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(343, 360, 21, 16))
        self.label_32 = QLabel(self.RDM_tab)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(369, 360, 21, 16))
        self.label_37 = QLabel(self.RDM_tab)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(396, 360, 21, 16))
        self.label_33 = QLabel(self.RDM_tab)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(423, 360, 21, 16))
        self.label_36 = QLabel(self.RDM_tab)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(450, 360, 21, 16))
        self.label_34 = QLabel(self.RDM_tab)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(477, 360, 21, 16))
        self.label_57 = QLabel(self.RDM_tab)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(503, 360, 21, 16))
        self.label_58 = QLabel(self.RDM_tab)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(530, 360, 21, 16))
        self.label_44 = QLabel(self.RDM_tab)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(21, 410, 21, 16))
        self.label_39 = QLabel(self.RDM_tab)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(48, 410, 21, 16))
        self.label_40 = QLabel(self.RDM_tab)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(75, 410, 21, 16))
        self.label_47 = QLabel(self.RDM_tab)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(101, 410, 21, 16))
        self.label_41 = QLabel(self.RDM_tab)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(128, 410, 21, 16))
        self.label_46 = QLabel(self.RDM_tab)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(155, 410, 21, 16))
        self.label_42 = QLabel(self.RDM_tab)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(182, 410, 21, 16))
        self.label_45 = QLabel(self.RDM_tab)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(209, 410, 21, 16))
        self.label_43 = QLabel(self.RDM_tab)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(235, 410, 21, 16))
        self.label_53 = QLabel(self.RDM_tab)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(262, 410, 21, 16))
        self.label_48 = QLabel(self.RDM_tab)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(289, 410, 21, 16))
        self.label_56 = QLabel(self.RDM_tab)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(343, 410, 21, 16))
        self.label_49 = QLabel(self.RDM_tab)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(316, 410, 21, 16))
        self.label_50 = QLabel(self.RDM_tab)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(369, 410, 21, 16))
        self.label_55 = QLabel(self.RDM_tab)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(396, 410, 21, 16))
        self.label_54 = QLabel(self.RDM_tab)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(450, 410, 21, 16))
        self.label_51 = QLabel(self.RDM_tab)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(423, 410, 21, 16))
        self.label_52 = QLabel(self.RDM_tab)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(477, 410, 21, 16))
        self.label_61 = QLabel(self.RDM_tab)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(503, 410, 21, 16))
        self.label_62 = QLabel(self.RDM_tab)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(530, 410, 21, 16))
        self.serialPort = QComboBox(self.RDM_tab)
        self.serialPort.setObjectName(u"serialPort")
        self.serialPort.setGeometry(QRect(110, 450, 68, 21))
        self.label_6 = QLabel(self.RDM_tab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(35, 450, 61, 21))
        self.refreshPorts = QPushButton(self.RDM_tab)
        self.refreshPorts.setObjectName(u"refreshPorts")
        self.refreshPorts.setGeometry(QRect(180, 445, 31, 31))
        self.refreshPorts.setStyleSheet(u"QPushButton{\n"
"\n"
"	background = rgb(10, 255, 100);\n"
"\n"
"}\n"
"")
        self.refreshPorts.setIcon(icon)
        self.refreshPorts.setIconSize(QSize(16, 16))
        self.refreshPorts.setAutoDefault(False)
        self.refreshPorts.setFlat(True)
        self.line = QFrame(self.RDM_tab)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(-5, 240, 591, 16))
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setFrameShape(QFrame.HLine)
        self.line_2 = QFrame(self.RDM_tab)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(-10, 475, 591, 16))
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_2.setFrameShape(QFrame.HLine)
        self.slaveResponse = QListWidget(self.RDM_tab)
        self.slaveResponse.setObjectName(u"slaveResponse")
        self.slaveResponse.setGeometry(QRect(5, 515, 561, 106))
        self.tabWidget.addTab(self.RDM_tab, "")
        self.DMX_tab = QWidget()
        self.DMX_tab.setObjectName(u"DMX_tab")
        self.label_14 = QLabel(self.DMX_tab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(325, 220, 46, 20))
        font4 = QFont()
        font4.setPointSize(9)
        font4.setBold(False)
        self.label_14.setFont(font4)
        self.blue_dmx_box = QSpinBox(self.DMX_tab)
        self.blue_dmx_box.setObjectName(u"blue_dmx_box")
        self.blue_dmx_box.setGeometry(QRect(390, 150, 46, 22))
        self.blue_dmx_box.setMaximum(255)
        self.send_command_dmx = QPushButton(self.DMX_tab)
        self.send_command_dmx.setObjectName(u"send_command_dmx")
        self.send_command_dmx.setGeometry(QRect(230, 495, 121, 24))
        self.green_dmx_box = QSpinBox(self.DMX_tab)
        self.green_dmx_box.setObjectName(u"green_dmx_box")
        self.green_dmx_box.setGeometry(QRect(390, 220, 46, 22))
        self.green_dmx_box.setMaximum(255)
        self.red_dmx_box = QSpinBox(self.DMX_tab)
        self.red_dmx_box.setObjectName(u"red_dmx_box")
        self.red_dmx_box.setGeometry(QRect(165, 215, 46, 22))
        self.red_dmx_box.setMaximum(255)
        self.label_7 = QLabel(self.DMX_tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(335, 150, 36, 20))
        self.label_7.setFont(font4)
        self.label_16 = QLabel(self.DMX_tab)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(85, 145, 61, 31))
        self.label_16.setFont(font4)
        self.DMX_address = QLineEdit(self.DMX_tab)
        self.DMX_address.setObjectName(u"DMX_address")
        self.DMX_address.setGeometry(QRect(455, 85, 41, 21))
        sizePolicy.setHeightForWidth(self.DMX_address.sizePolicy().hasHeightForWidth())
        self.DMX_address.setSizePolicy(sizePolicy)
        self.DMX_address.setBaseSize(QSize(0, 0))
        self.DMX_address.setFrame(True)
        self.label_17 = QLabel(self.DMX_tab)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(285, 85, 141, 20))
        self.label_17.setFont(font1)
        self.label_18 = QLabel(self.DMX_tab)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(75, 205, 71, 36))
        self.label_18.setFont(font4)
        self.white_dmx_box = QSpinBox(self.DMX_tab)
        self.white_dmx_box.setObjectName(u"white_dmx_box")
        self.white_dmx_box.setGeometry(QRect(165, 150, 46, 22))
        self.white_dmx_box.setMaximum(255)
        self.label_19 = QLabel(self.DMX_tab)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(220, 10, 141, 41))
        self.label_19.setFont(font2)
        self.white_dmx_slider = QSlider(self.DMX_tab)
        self.white_dmx_slider.setObjectName(u"white_dmx_slider")
        self.white_dmx_slider.setGeometry(QRect(225, 135, 18, 51))
        self.white_dmx_slider.setStyleSheet(u"QSlider::handle:vertical{\n"
"	height: 4px;\n"
"	background-color: rgb(255, 255, 255);\n"
" 	margin: 1px; /* expand outside the groove */\n"
"	border-radius: 4px;\n"
"	border: 1px solid black;\n"
"	width: 8px;\n"
"}\n"
"")
        self.white_dmx_slider.setMaximum(255)
        self.white_dmx_slider.setOrientation(Qt.Vertical)
        self.green_dmx_slider = QSlider(self.DMX_tab)
        self.green_dmx_slider.setObjectName(u"green_dmx_slider")
        self.green_dmx_slider.setGeometry(QRect(450, 205, 18, 51))
        self.green_dmx_slider.setStyleSheet(u"QSlider::handle:vertical{\n"
"	height: 4px;\n"
"	background-color: rgb(0, 255, 0);\n"
" 	margin: 1px; /* expand outside the groove */\n"
"	border-radius: 4px;\n"
"	border: 1px solid black;\n"
"	width: 8px;\n"
"}\n"
"")
        self.green_dmx_slider.setMaximum(255)
        self.green_dmx_slider.setOrientation(Qt.Vertical)
        self.red_dmx_slider = QSlider(self.DMX_tab)
        self.red_dmx_slider.setObjectName(u"red_dmx_slider")
        self.red_dmx_slider.setGeometry(QRect(225, 200, 18, 51))
        self.red_dmx_slider.setStyleSheet(u"QSlider::handle:vertical{\n"
"	height: 4px;\n"
"	background-color: rgb(255, 0, 0);\n"
" 	margin: 1px; /* expand outside the groove */\n"
"	border-radius: 4px;\n"
"	border: 1px solid black;\n"
"	width: 8px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.red_dmx_slider.setMaximum(255)
        self.red_dmx_slider.setOrientation(Qt.Vertical)
        self.blue_dmx_slider = QSlider(self.DMX_tab)
        self.blue_dmx_slider.setObjectName(u"blue_dmx_slider")
        self.blue_dmx_slider.setGeometry(QRect(450, 135, 18, 51))
        self.blue_dmx_slider.setStyleSheet(u"QSlider::handle:vertical{\n"
"	height: 4px;\n"
"	background-color: rgb(0, 0, 255);\n"
" 	margin: 1px; /* expand outside the groove */\n"
"	border-radius: 4px;\n"
"	border: 1px solid black;\n"
"	width: 8px;\n"
"}\n"
"")
        self.blue_dmx_slider.setMaximum(255)
        self.blue_dmx_slider.setOrientation(Qt.Vertical)
        self.RGB_dmx_slider = QSlider(self.DMX_tab)
        self.RGB_dmx_slider.setObjectName(u"RGB_dmx_slider")
        self.RGB_dmx_slider.setGeometry(QRect(45, 280, 476, 26))
        self.RGB_dmx_slider.setLayoutDirection(Qt.LeftToRight)
        self.RGB_dmx_slider.setStyleSheet(u"QSlider::handle:horizontal\n"
"{\n"
"    background: rgb(255, 255, 255);\n"
"    width: 6px;\n"
"    height: 12px;\n"
"	margin: 2px 0px;\n"
"    border-radius: 7px;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"\n"
"}\n"
"QSlider::groove:horizontal\n"
"{\n"
"	border-radius: 2px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));\n"
"\n"
"}")
        self.RGB_dmx_slider.setMaximum(768)
        self.RGB_dmx_slider.setOrientation(Qt.Horizontal)
        self.RGB_dmx_slider.setTickPosition(QSlider.NoTicks)
        self.RGB_dmx_slider.setTickInterval(10)
        self.autoSend_dmx_command = QCheckBox(self.DMX_tab)
        self.autoSend_dmx_command.setObjectName(u"autoSend_dmx_command")
        self.autoSend_dmx_command.setGeometry(QRect(220, 515, 151, 26))
        self.line_3 = QFrame(self.DMX_tab)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(-5, 315, 591, 16))
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_4 = QFrame(self.DMX_tab)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(-10, 120, 591, 16))
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_4.setFrameShape(QFrame.HLine)
        self.label_12 = QLabel(self.DMX_tab)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(435, 85, 20, 20))
        self.label_15 = QLabel(self.DMX_tab)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(200, 330, 206, 16))
        font5 = QFont()
        font5.setBold(True)
        self.label_15.setFont(font5)
        self.label_71 = QLabel(self.DMX_tab)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(100, 85, 86, 20))
        self.label_71.setFont(font1)
        self.DMX_command_label = QListWidget(self.DMX_tab)
        QListWidgetItem(self.DMX_command_label)
        self.DMX_command_label.setObjectName(u"DMX_command_label")
        self.DMX_command_label.setGeometry(QRect(15, 355, 541, 131))
        font6 = QFont()
        font6.setPointSize(8)
        self.DMX_command_label.setFont(font6)
        self.Slots_per_link = QSpinBox(self.DMX_tab)
        self.Slots_per_link.setObjectName(u"Slots_per_link")
        self.Slots_per_link.setGeometry(QRect(190, 85, 56, 22))
        self.Slots_per_link.setMinimum(5)
        self.Slots_per_link.setMaximum(513)
        self.tabWidget.addTab(self.DMX_tab, "")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 580, 22))
        self.menuAjuda = QMenu(self.menubar)
        self.menuAjuda.setObjectName(u"menuAjuda")
        self.menuSair = QMenu(self.menubar)
        self.menuSair.setObjectName(u"menuSair")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        #MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.source_UID, self.parametro)
        QWidget.setTabOrder(self.parametro, self.white_dmx_slider)
        QWidget.setTabOrder(self.white_dmx_slider, self.port_ID)
        QWidget.setTabOrder(self.port_ID, self.classe)
        QWidget.setTabOrder(self.classe, self.send_command)
        QWidget.setTabOrder(self.send_command, self.destination_UID)
        QWidget.setTabOrder(self.destination_UID, self.sub_device)
        QWidget.setTabOrder(self.sub_device, self.command_1)
        QWidget.setTabOrder(self.command_1, self.command_2)
        QWidget.setTabOrder(self.command_2, self.command_4)
        QWidget.setTabOrder(self.command_4, self.command_3)
        QWidget.setTabOrder(self.command_3, self.command_6)
        QWidget.setTabOrder(self.command_6, self.command_8)
        QWidget.setTabOrder(self.command_8, self.command_7)
        QWidget.setTabOrder(self.command_7, self.command_5)
        QWidget.setTabOrder(self.command_5, self.command_14)
        QWidget.setTabOrder(self.command_14, self.command_10)
        QWidget.setTabOrder(self.command_10, self.command_16)
        QWidget.setTabOrder(self.command_16, self.command_12)
        QWidget.setTabOrder(self.command_12, self.command_15)
        QWidget.setTabOrder(self.command_15, self.command_11)
        QWidget.setTabOrder(self.command_11, self.command_13)
        QWidget.setTabOrder(self.command_13, self.command_9)
        QWidget.setTabOrder(self.command_9, self.command_20)
        QWidget.setTabOrder(self.command_20, self.command_18)
        QWidget.setTabOrder(self.command_18, self.command_19)
        QWidget.setTabOrder(self.command_19, self.command_17)
        QWidget.setTabOrder(self.command_17, self.command_26)
        QWidget.setTabOrder(self.command_26, self.command_31)
        QWidget.setTabOrder(self.command_31, self.command_32)
        QWidget.setTabOrder(self.command_32, self.command_29)
        QWidget.setTabOrder(self.command_29, self.command_37)
        QWidget.setTabOrder(self.command_37, self.command_30)
        QWidget.setTabOrder(self.command_30, self.command_22)
        QWidget.setTabOrder(self.command_22, self.command_36)
        QWidget.setTabOrder(self.command_36, self.command_28)
        QWidget.setTabOrder(self.command_28, self.command_24)
        QWidget.setTabOrder(self.command_24, self.command_27)
        QWidget.setTabOrder(self.command_27, self.command_23)
        QWidget.setTabOrder(self.command_23, self.command_25)
        QWidget.setTabOrder(self.command_25, self.command_21)
        QWidget.setTabOrder(self.command_21, self.command_34)
        QWidget.setTabOrder(self.command_34, self.command_33)
        QWidget.setTabOrder(self.command_33, self.command_35)
        QWidget.setTabOrder(self.command_35, self.command_38)
        QWidget.setTabOrder(self.command_38, self.command_40)
        QWidget.setTabOrder(self.command_40, self.command_39)
        QWidget.setTabOrder(self.command_39, self.add_param_1)
        QWidget.setTabOrder(self.add_param_1, self.add_param_2)
        QWidget.setTabOrder(self.add_param_2, self.frame_size)
        QWidget.setTabOrder(self.frame_size, self.serialPort)
        QWidget.setTabOrder(self.serialPort, self.blue_dmx_box)
        QWidget.setTabOrder(self.blue_dmx_box, self.send_command_dmx)
        QWidget.setTabOrder(self.send_command_dmx, self.green_dmx_box)
        QWidget.setTabOrder(self.green_dmx_box, self.red_dmx_box)
        QWidget.setTabOrder(self.red_dmx_box, self.DMX_address)
        QWidget.setTabOrder(self.DMX_address, self.white_dmx_box)
        QWidget.setTabOrder(self.white_dmx_box, self.tabWidget)
        QWidget.setTabOrder(self.tabWidget, self.green_dmx_slider)
        QWidget.setTabOrder(self.green_dmx_slider, self.red_dmx_slider)
        QWidget.setTabOrder(self.red_dmx_slider, self.blue_dmx_slider)
        QWidget.setTabOrder(self.blue_dmx_slider, self.RGB_dmx_slider)
        QWidget.setTabOrder(self.RGB_dmx_slider, self.autoSend_dmx_command)
        QWidget.setTabOrder(self.autoSend_dmx_command, self.refreshPorts)

        self.menubar.addAction(self.menuSair.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.refreshPorts.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionDMX.setText(QCoreApplication.translate("MainWindow", u"RDM", None))
        self.actionRDM.setText(QCoreApplication.translate("MainWindow", u"DMX", None))
        self.actionReload.setText(QCoreApplication.translate("MainWindow", u"Reload", None))
#if QT_CONFIG(tooltip)
        self.actionReload.setToolTip(QCoreApplication.translate("MainWindow", u"reload something", None))
#endif // QT_CONFIG(tooltip)
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Resposta do slave", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Comando", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Par\u00e2metro", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u" 0x", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"RDM - Master", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u" 0x", None))
        self.UID_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">UID de destino</p></body></html>", None))
        self.parametro.setItemText(0, QCoreApplication.translate("MainWindow", u"Unique Branch", None))
        self.parametro.setItemText(1, QCoreApplication.translate("MainWindow", u"Mute", None))
        self.parametro.setItemText(2, QCoreApplication.translate("MainWindow", u"Unmute", None))

        self.UID_S_Label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">UID da fonte</p></body></html>", None))
        self.Subdevice_label.setText(QCoreApplication.translate("MainWindow", u"Sub device", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u" 0x", None))
        self.classe.setItemText(0, QCoreApplication.translate("MainWindow", u"DISC", None))
        self.classe.setItemText(1, QCoreApplication.translate("MainWindow", u"GET", None))
        self.classe.setItemText(2, QCoreApplication.translate("MainWindow", u"SET", None))

        self.label.setText(QCoreApplication.translate("MainWindow", u"Classe", None))
        self.send_command.setText(QCoreApplication.translate("MainWindow", u"Enviar comando", None))
        self.Portid_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\">Port ID</p></body></html>", None))
        self.destination_UID.setInputMask("")
        self.destination_UID.setText("")
        self.command_1.setText("")
        self.command_2.setText("")
        self.command_4.setText("")
        self.command_3.setText("")
        self.command_6.setText("")
        self.command_8.setText("")
        self.command_7.setText("")
        self.command_5.setText("")
        self.command_14.setText("")
        self.command_10.setText("")
        self.command_16.setText("")
        self.command_12.setText("")
        self.command_15.setText("")
        self.command_11.setText("")
        self.command_13.setText("")
        self.command_9.setText("")
        self.command_20.setText("")
        self.command_18.setText("")
        self.command_19.setText("")
        self.command_17.setText("")
        self.command_26.setText("")
        self.command_31.setText("")
        self.command_32.setText("")
        self.command_29.setText("")
        self.command_37.setText("")
        self.command_30.setText("")
        self.command_22.setText("")
        self.command_36.setText("")
        self.command_28.setText("")
        self.command_24.setText("")
        self.command_27.setText("")
        self.command_23.setText("")
        self.command_25.setText("")
        self.command_21.setText("")
        self.command_34.setText("")
        self.command_33.setText("")
        self.command_35.setText("")
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Comando a ser enviado byte a byte em hexadecimal</span></p></body></html>", None))
        self.command_38.setText("")
        self.command_40.setText("")
        self.command_39.setText("")
        self.add_param_1_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"/></body></html>", None))
        self.label_63.setText(QCoreApplication.translate("MainWindow", u" 0x", None))
        self.label_64.setText(QCoreApplication.translate("MainWindow", u" 0x", None))
        self.add_param_2_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"/></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Tamanho do frame</span></p></body></html>", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u" 0x", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">02</p></body></html>", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">01</p></body></html>", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">03</p></body></html>", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">04</p></body></html>", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">06</p></body></html>", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">05</p></body></html>", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">07</p></body></html>", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">08</p></body></html>", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">09</p></body></html>", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">10</p></body></html>", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">11</p></body></html>", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">12</p></body></html>", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">13</p></body></html>", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">14</p></body></html>", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">15</p></body></html>", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">16</p></body></html>", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">17</p></body></html>", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">18</p></body></html>", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">19</p></body></html>", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">20</p></body></html>", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">21</p></body></html>", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">22</p></body></html>", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">23</p></body></html>", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">24</p></body></html>", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">25</p></body></html>", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">26</p></body></html>", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">27</p></body></html>", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">28</p></body></html>", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">29</p></body></html>", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">30</p></body></html>", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">31</p></body></html>", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">33</p></body></html>", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">32</p></body></html>", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">34</p></body></html>", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">35</p></body></html>", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">37</p></body></html>", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">36</p></body></html>", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">38</p></body></html>", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">39</p></body></html>", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\">40</p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Porta serial", None))
        self.refreshPorts.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RDM_tab), QCoreApplication.translate("MainWindow", u"Modo RDM", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Verde</span></p></body></html>", None))
        self.send_command_dmx.setText(QCoreApplication.translate("MainWindow", u"Enviar comando", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Azul</span></p></body></html>", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Branco</span></p></body></html>", None))
        self.DMX_address.setInputMask("")
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Endere\u00e7o da lumin\u00e1ria", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><span style=\" font-size:12pt;\">Vermelho</span></p></body></html>", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"DMX - Master", None))
        self.autoSend_dmx_command.setText(QCoreApplication.translate("MainWindow", u"Enviar automaticamente", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u" 0x", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Frame a ser enviado em exadecimal", None))
        self.label_71.setText(QCoreApplication.translate("MainWindow", u"Slots por link", None))

        __sortingEnabled = self.DMX_command_label.isSortingEnabled()
        self.DMX_command_label.setSortingEnabled(False)
        ___qlistwidgetitem = self.DMX_command_label.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"000 -  00 00 00 00 00 00 00 00 00 00 00 00 AD 2A 00 AA 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00", None));
        self.DMX_command_label.setSortingEnabled(__sortingEnabled)

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DMX_tab), QCoreApplication.translate("MainWindow", u"Modo DMX", None))
        self.menuAjuda.setTitle(QCoreApplication.translate("MainWindow", u"Ajuda", None))
        self.menuSair.setTitle(QCoreApplication.translate("MainWindow", u"Sair", None))
    # retranslateUi

