# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'RDM_DMX_Master.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSpinBox, QStatusBar, QTabWidget,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(450, 632)
        self.actionDMX = QAction(MainWindow)
        self.actionDMX.setObjectName(u"actionDMX")
        self.actionRDM = QAction(MainWindow)
        self.actionRDM.setObjectName(u"actionRDM")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 20, 451, 601))
        palette = QPalette()
        brush = QBrush(QColor(225, 225, 225, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        self.tabWidget.setPalette(palette)
        self.RDM_tab = QWidget()
        self.RDM_tab.setObjectName(u"RDM_tab")
        self.label_9 = QLabel(self.RDM_tab)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(160, 470, 121, 20))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setWordWrap(False)
        self.label_3 = QLabel(self.RDM_tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 70, 61, 20))
        self.label_3.setFont(font)
        self.label_2 = QLabel(self.RDM_tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(270, 50, 61, 16))
        self.label_10 = QLabel(self.RDM_tab)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(170, 110, 16, 16))
        self.label_4 = QLabel(self.RDM_tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(150, 10, 141, 41))
        font1 = QFont()
        font1.setPointSize(16)
        font1.setBold(True)
        self.label_4.setFont(font1)
        self.label_11 = QLabel(self.RDM_tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(170, 150, 16, 16))
        self.source_UID = QLineEdit(self.RDM_tab)
        self.source_UID.setObjectName(u"source_UID")
        self.source_UID.setGeometry(QRect(190, 150, 221, 21))
        self.source_UID.setFrame(True)
        self.slave_Response = QLabel(self.RDM_tab)
        self.slave_Response.setObjectName(u"slave_Response")
        self.slave_Response.setGeometry(QRect(20, 490, 411, 51))
        self.slave_Response.setAutoFillBackground(True)
        self.UID_label = QLabel(self.RDM_tab)
        self.UID_label.setObjectName(u"UID_label")
        self.UID_label.setGeometry(QRect(40, 110, 101, 20))
        self.UID_label.setFont(font)
        self.parametro = QComboBox(self.RDM_tab)
        self.parametro.addItem("")
        self.parametro.addItem("")
        self.parametro.addItem("")
        self.parametro.setObjectName(u"parametro")
        self.parametro.setGeometry(QRect(190, 70, 221, 22))
        self.UID_S_Label = QLabel(self.RDM_tab)
        self.UID_S_Label.setObjectName(u"UID_S_Label")
        self.UID_S_Label.setGeometry(QRect(40, 150, 101, 20))
        self.UID_S_Label.setFont(font)
        self.port_ID = QLineEdit(self.RDM_tab)
        self.port_ID.setObjectName(u"port_ID")
        self.port_ID.setGeometry(QRect(190, 230, 221, 21))
        self.port_ID.setMaxLength(32767)
        self.port_ID.setFrame(True)
        self.Subdevice_label = QLabel(self.RDM_tab)
        self.Subdevice_label.setObjectName(u"Subdevice_label")
        self.Subdevice_label.setGeometry(QRect(40, 190, 101, 20))
        self.Subdevice_label.setFont(font)
        self.label_13 = QLabel(self.RDM_tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(170, 230, 16, 16))
        self.classe = QComboBox(self.RDM_tab)
        self.classe.addItem("")
        self.classe.addItem("")
        self.classe.addItem("")
        self.classe.setObjectName(u"classe")
        self.classe.setGeometry(QRect(110, 70, 68, 22))
        self.label_12 = QLabel(self.RDM_tab)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(170, 190, 16, 16))
        self.label = QLabel(self.RDM_tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(130, 50, 49, 16))
        self.send_command = QPushButton(self.RDM_tab)
        self.send_command.setObjectName(u"send_command")
        self.send_command.setGeometry(QRect(150, 440, 121, 24))
        self.Portid_label = QLabel(self.RDM_tab)
        self.Portid_label.setObjectName(u"Portid_label")
        self.Portid_label.setGeometry(QRect(40, 230, 101, 20))
        self.Portid_label.setFont(font)
        self.destination_UID = QLineEdit(self.RDM_tab)
        self.destination_UID.setObjectName(u"destination_UID")
        self.destination_UID.setGeometry(QRect(190, 110, 221, 21))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.destination_UID.sizePolicy().hasHeightForWidth())
        self.destination_UID.setSizePolicy(sizePolicy)
        self.destination_UID.setBaseSize(QSize(0, 0))
        self.destination_UID.setFrame(True)
        self.sub_device = QLineEdit(self.RDM_tab)
        self.sub_device.setObjectName(u"sub_device")
        self.sub_device.setGeometry(QRect(190, 190, 221, 21))
        self.sub_device.setFrame(True)
        self.command_1 = QLineEdit(self.RDM_tab)
        self.command_1.setObjectName(u"command_1")
        self.command_1.setGeometry(QRect(30, 350, 16, 21))
        self.command_1.setLayoutDirection(Qt.LeftToRight)
        self.command_1.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_1.setReadOnly(False)
        self.command_2 = QLineEdit(self.RDM_tab)
        self.command_2.setObjectName(u"command_2")
        self.command_2.setGeometry(QRect(50, 350, 16, 21))
        self.command_2.setLayoutDirection(Qt.LeftToRight)
        self.command_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_2.setReadOnly(False)
        self.command_4 = QLineEdit(self.RDM_tab)
        self.command_4.setObjectName(u"command_4")
        self.command_4.setGeometry(QRect(90, 350, 16, 21))
        self.command_4.setLayoutDirection(Qt.LeftToRight)
        self.command_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_4.setReadOnly(False)
        self.command_3 = QLineEdit(self.RDM_tab)
        self.command_3.setObjectName(u"command_3")
        self.command_3.setGeometry(QRect(70, 350, 16, 21))
        self.command_3.setLayoutDirection(Qt.LeftToRight)
        self.command_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_3.setReadOnly(False)
        self.command_6 = QLineEdit(self.RDM_tab)
        self.command_6.setObjectName(u"command_6")
        self.command_6.setGeometry(QRect(130, 350, 16, 21))
        self.command_6.setLayoutDirection(Qt.LeftToRight)
        self.command_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_6.setReadOnly(False)
        self.command_8 = QLineEdit(self.RDM_tab)
        self.command_8.setObjectName(u"command_8")
        self.command_8.setGeometry(QRect(170, 350, 16, 21))
        self.command_8.setLayoutDirection(Qt.LeftToRight)
        self.command_8.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_8.setReadOnly(False)
        self.command_7 = QLineEdit(self.RDM_tab)
        self.command_7.setObjectName(u"command_7")
        self.command_7.setGeometry(QRect(150, 350, 16, 21))
        self.command_7.setLayoutDirection(Qt.LeftToRight)
        self.command_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_7.setReadOnly(False)
        self.command_5 = QLineEdit(self.RDM_tab)
        self.command_5.setObjectName(u"command_5")
        self.command_5.setGeometry(QRect(110, 350, 16, 21))
        self.command_5.setLayoutDirection(Qt.LeftToRight)
        self.command_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_5.setReadOnly(False)
        self.command_14 = QLineEdit(self.RDM_tab)
        self.command_14.setObjectName(u"command_14")
        self.command_14.setGeometry(QRect(290, 350, 16, 21))
        self.command_14.setLayoutDirection(Qt.LeftToRight)
        self.command_14.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_14.setReadOnly(False)
        self.command_10 = QLineEdit(self.RDM_tab)
        self.command_10.setObjectName(u"command_10")
        self.command_10.setGeometry(QRect(210, 350, 16, 21))
        self.command_10.setLayoutDirection(Qt.LeftToRight)
        self.command_10.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_10.setReadOnly(False)
        self.command_16 = QLineEdit(self.RDM_tab)
        self.command_16.setObjectName(u"command_16")
        self.command_16.setGeometry(QRect(330, 350, 16, 21))
        self.command_16.setLayoutDirection(Qt.LeftToRight)
        self.command_16.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_16.setReadOnly(False)
        self.command_12 = QLineEdit(self.RDM_tab)
        self.command_12.setObjectName(u"command_12")
        self.command_12.setGeometry(QRect(250, 350, 16, 21))
        self.command_12.setLayoutDirection(Qt.LeftToRight)
        self.command_12.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_12.setReadOnly(False)
        self.command_15 = QLineEdit(self.RDM_tab)
        self.command_15.setObjectName(u"command_15")
        self.command_15.setGeometry(QRect(310, 350, 16, 21))
        self.command_15.setLayoutDirection(Qt.LeftToRight)
        self.command_15.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_15.setReadOnly(False)
        self.command_11 = QLineEdit(self.RDM_tab)
        self.command_11.setObjectName(u"command_11")
        self.command_11.setGeometry(QRect(230, 350, 16, 21))
        self.command_11.setLayoutDirection(Qt.LeftToRight)
        self.command_11.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_11.setReadOnly(False)
        self.command_13 = QLineEdit(self.RDM_tab)
        self.command_13.setObjectName(u"command_13")
        self.command_13.setGeometry(QRect(270, 350, 16, 21))
        self.command_13.setLayoutDirection(Qt.LeftToRight)
        self.command_13.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_13.setReadOnly(False)
        self.command_9 = QLineEdit(self.RDM_tab)
        self.command_9.setObjectName(u"command_9")
        self.command_9.setGeometry(QRect(190, 350, 16, 21))
        self.command_9.setLayoutDirection(Qt.LeftToRight)
        self.command_9.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_9.setReadOnly(False)
        self.command_20 = QLineEdit(self.RDM_tab)
        self.command_20.setObjectName(u"command_20")
        self.command_20.setGeometry(QRect(410, 350, 16, 21))
        self.command_20.setLayoutDirection(Qt.LeftToRight)
        self.command_20.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_20.setReadOnly(False)
        self.command_18 = QLineEdit(self.RDM_tab)
        self.command_18.setObjectName(u"command_18")
        self.command_18.setGeometry(QRect(370, 350, 16, 21))
        self.command_18.setLayoutDirection(Qt.LeftToRight)
        self.command_18.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_18.setReadOnly(False)
        self.command_19 = QLineEdit(self.RDM_tab)
        self.command_19.setObjectName(u"command_19")
        self.command_19.setGeometry(QRect(390, 350, 16, 21))
        self.command_19.setLayoutDirection(Qt.LeftToRight)
        self.command_19.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_19.setReadOnly(False)
        self.command_17 = QLineEdit(self.RDM_tab)
        self.command_17.setObjectName(u"command_17")
        self.command_17.setGeometry(QRect(350, 350, 16, 21))
        self.command_17.setLayoutDirection(Qt.LeftToRight)
        self.command_17.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_17.setReadOnly(False)
        self.command_26 = QLineEdit(self.RDM_tab)
        self.command_26.setObjectName(u"command_26")
        self.command_26.setGeometry(QRect(130, 390, 16, 21))
        self.command_26.setLayoutDirection(Qt.LeftToRight)
        self.command_26.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_26.setReadOnly(False)
        self.command_31 = QLineEdit(self.RDM_tab)
        self.command_31.setObjectName(u"command_31")
        self.command_31.setGeometry(QRect(230, 390, 16, 21))
        self.command_31.setLayoutDirection(Qt.LeftToRight)
        self.command_31.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_31.setReadOnly(False)
        self.command_32 = QLineEdit(self.RDM_tab)
        self.command_32.setObjectName(u"command_32")
        self.command_32.setGeometry(QRect(250, 390, 16, 21))
        self.command_32.setLayoutDirection(Qt.LeftToRight)
        self.command_32.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_32.setReadOnly(False)
        self.command_29 = QLineEdit(self.RDM_tab)
        self.command_29.setObjectName(u"command_29")
        self.command_29.setGeometry(QRect(190, 390, 16, 21))
        self.command_29.setLayoutDirection(Qt.LeftToRight)
        self.command_29.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_29.setReadOnly(False)
        self.command_37 = QLineEdit(self.RDM_tab)
        self.command_37.setObjectName(u"command_37")
        self.command_37.setGeometry(QRect(350, 390, 16, 21))
        self.command_37.setLayoutDirection(Qt.LeftToRight)
        self.command_37.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_37.setReadOnly(False)
        self.command_30 = QLineEdit(self.RDM_tab)
        self.command_30.setObjectName(u"command_30")
        self.command_30.setGeometry(QRect(210, 390, 16, 21))
        self.command_30.setLayoutDirection(Qt.LeftToRight)
        self.command_30.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_30.setReadOnly(False)
        self.command_22 = QLineEdit(self.RDM_tab)
        self.command_22.setObjectName(u"command_22")
        self.command_22.setGeometry(QRect(50, 390, 16, 21))
        self.command_22.setLayoutDirection(Qt.LeftToRight)
        self.command_22.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_22.setReadOnly(False)
        self.command_36 = QLineEdit(self.RDM_tab)
        self.command_36.setObjectName(u"command_36")
        self.command_36.setGeometry(QRect(330, 390, 16, 21))
        self.command_36.setLayoutDirection(Qt.LeftToRight)
        self.command_36.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_36.setReadOnly(False)
        self.command_28 = QLineEdit(self.RDM_tab)
        self.command_28.setObjectName(u"command_28")
        self.command_28.setGeometry(QRect(170, 390, 16, 21))
        self.command_28.setLayoutDirection(Qt.LeftToRight)
        self.command_28.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_28.setReadOnly(False)
        self.command_24 = QLineEdit(self.RDM_tab)
        self.command_24.setObjectName(u"command_24")
        self.command_24.setGeometry(QRect(90, 390, 16, 21))
        self.command_24.setLayoutDirection(Qt.LeftToRight)
        self.command_24.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_24.setReadOnly(False)
        self.command_27 = QLineEdit(self.RDM_tab)
        self.command_27.setObjectName(u"command_27")
        self.command_27.setGeometry(QRect(150, 390, 16, 21))
        self.command_27.setLayoutDirection(Qt.LeftToRight)
        self.command_27.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_27.setReadOnly(False)
        self.command_23 = QLineEdit(self.RDM_tab)
        self.command_23.setObjectName(u"command_23")
        self.command_23.setGeometry(QRect(70, 390, 16, 21))
        self.command_23.setLayoutDirection(Qt.LeftToRight)
        self.command_23.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_23.setReadOnly(False)
        self.command_25 = QLineEdit(self.RDM_tab)
        self.command_25.setObjectName(u"command_25")
        self.command_25.setGeometry(QRect(110, 390, 16, 21))
        self.command_25.setLayoutDirection(Qt.LeftToRight)
        self.command_25.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_25.setReadOnly(False)
        self.command_21 = QLineEdit(self.RDM_tab)
        self.command_21.setObjectName(u"command_21")
        self.command_21.setGeometry(QRect(30, 390, 16, 21))
        self.command_21.setLayoutDirection(Qt.LeftToRight)
        self.command_21.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_21.setReadOnly(False)
        self.command_34 = QLineEdit(self.RDM_tab)
        self.command_34.setObjectName(u"command_34")
        self.command_34.setGeometry(QRect(290, 390, 16, 21))
        self.command_34.setLayoutDirection(Qt.LeftToRight)
        self.command_34.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_34.setReadOnly(False)
        self.command_33 = QLineEdit(self.RDM_tab)
        self.command_33.setObjectName(u"command_33")
        self.command_33.setGeometry(QRect(270, 390, 16, 21))
        self.command_33.setLayoutDirection(Qt.LeftToRight)
        self.command_33.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_33.setReadOnly(False)
        self.command_35 = QLineEdit(self.RDM_tab)
        self.command_35.setObjectName(u"command_35")
        self.command_35.setGeometry(QRect(310, 390, 16, 21))
        self.command_35.setLayoutDirection(Qt.LeftToRight)
        self.command_35.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_35.setReadOnly(False)
        self.label_20 = QLabel(self.RDM_tab)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(90, 320, 291, 20))
        self.label_21 = QLabel(self.RDM_tab)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(30, 370, 16, 16))
        self.label_22 = QLabel(self.RDM_tab)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(50, 370, 16, 16))
        self.label_23 = QLabel(self.RDM_tab)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(70, 370, 16, 16))
        self.label_24 = QLabel(self.RDM_tab)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(110, 370, 16, 16))
        self.label_25 = QLabel(self.RDM_tab)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(130, 370, 16, 16))
        self.label_26 = QLabel(self.RDM_tab)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(90, 370, 16, 16))
        self.label_27 = QLabel(self.RDM_tab)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(170, 370, 16, 16))
        self.label_28 = QLabel(self.RDM_tab)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(190, 370, 16, 16))
        self.label_29 = QLabel(self.RDM_tab)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(150, 370, 16, 16))
        self.label_30 = QLabel(self.RDM_tab)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(230, 370, 16, 16))
        self.label_31 = QLabel(self.RDM_tab)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(250, 370, 16, 16))
        self.label_32 = QLabel(self.RDM_tab)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(290, 370, 16, 16))
        self.label_33 = QLabel(self.RDM_tab)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(330, 370, 16, 16))
        self.label_34 = QLabel(self.RDM_tab)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(370, 370, 16, 16))
        self.label_35 = QLabel(self.RDM_tab)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(210, 370, 16, 16))
        self.label_36 = QLabel(self.RDM_tab)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(350, 370, 16, 16))
        self.label_37 = QLabel(self.RDM_tab)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(310, 370, 16, 16))
        self.label_38 = QLabel(self.RDM_tab)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(270, 370, 16, 16))
        self.label_39 = QLabel(self.RDM_tab)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(50, 410, 16, 16))
        self.label_40 = QLabel(self.RDM_tab)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(70, 410, 16, 16))
        self.label_41 = QLabel(self.RDM_tab)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(110, 410, 16, 16))
        self.label_42 = QLabel(self.RDM_tab)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(150, 410, 16, 16))
        self.label_43 = QLabel(self.RDM_tab)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(190, 410, 16, 16))
        self.label_44 = QLabel(self.RDM_tab)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(30, 410, 16, 16))
        self.label_45 = QLabel(self.RDM_tab)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(170, 410, 16, 16))
        self.label_46 = QLabel(self.RDM_tab)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(130, 410, 16, 16))
        self.label_47 = QLabel(self.RDM_tab)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(90, 410, 16, 16))
        self.label_48 = QLabel(self.RDM_tab)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(230, 410, 16, 16))
        self.label_49 = QLabel(self.RDM_tab)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(250, 410, 16, 16))
        self.label_50 = QLabel(self.RDM_tab)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(290, 410, 16, 16))
        self.label_51 = QLabel(self.RDM_tab)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(330, 410, 16, 16))
        self.label_52 = QLabel(self.RDM_tab)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(370, 410, 16, 16))
        self.label_53 = QLabel(self.RDM_tab)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(210, 410, 16, 16))
        self.label_54 = QLabel(self.RDM_tab)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(350, 410, 16, 16))
        self.label_55 = QLabel(self.RDM_tab)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(310, 410, 16, 16))
        self.label_56 = QLabel(self.RDM_tab)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(270, 410, 16, 16))
        self.label_57 = QLabel(self.RDM_tab)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(390, 370, 16, 16))
        self.label_58 = QLabel(self.RDM_tab)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(410, 370, 16, 16))
        self.command_41 = QLineEdit(self.RDM_tab)
        self.command_41.setObjectName(u"command_41")
        self.command_41.setGeometry(QRect(370, 390, 16, 21))
        self.command_41.setLayoutDirection(Qt.LeftToRight)
        self.command_41.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_41.setReadOnly(False)
        self.command_42 = QLineEdit(self.RDM_tab)
        self.command_42.setObjectName(u"command_42")
        self.command_42.setGeometry(QRect(410, 390, 16, 21))
        self.command_42.setLayoutDirection(Qt.LeftToRight)
        self.command_42.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_42.setReadOnly(False)
        self.label_61 = QLabel(self.RDM_tab)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(390, 410, 16, 16))
        self.command_43 = QLineEdit(self.RDM_tab)
        self.command_43.setObjectName(u"command_43")
        self.command_43.setGeometry(QRect(390, 390, 16, 21))
        self.command_43.setLayoutDirection(Qt.LeftToRight)
        self.command_43.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.command_43.setReadOnly(False)
        self.label_62 = QLabel(self.RDM_tab)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(410, 410, 16, 16))
        self.additional_parameter = QLineEdit(self.RDM_tab)
        self.additional_parameter.setObjectName(u"additional_parameter")
        self.additional_parameter.setEnabled(False)
        self.additional_parameter.setGeometry(QRect(190, 270, 221, 21))
        self.additional_parameter.setMaxLength(32767)
        self.additional_parameter.setFrame(True)
        self.additional_command = QLabel(self.RDM_tab)
        self.additional_command.setObjectName(u"additional_command")
        self.additional_command.setEnabled(True)
        self.additional_command.setGeometry(QRect(40, 270, 101, 20))
        self.additional_command.setFont(font)
        self.label_63 = QLabel(self.RDM_tab)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setEnabled(True)
        self.label_63.setGeometry(QRect(170, 270, 16, 16))
        self.tabWidget.addTab(self.RDM_tab, "")
        self.DMX_tab = QWidget()
        self.DMX_tab.setObjectName(u"DMX_tab")
        self.label_14 = QLabel(self.DMX_tab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(240, 250, 101, 20))
        font2 = QFont()
        font2.setPointSize(9)
        font2.setBold(False)
        self.label_14.setFont(font2)
        self.spinBox_2 = QSpinBox(self.DMX_tab)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(280, 210, 91, 22))
        self.send_command_2 = QPushButton(self.DMX_tab)
        self.send_command_2.setObjectName(u"send_command_2")
        self.send_command_2.setGeometry(QRect(160, 340, 121, 24))
        self.spinBox_3 = QSpinBox(self.DMX_tab)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(280, 250, 91, 22))
        self.spinBox_4 = QSpinBox(self.DMX_tab)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(130, 250, 91, 22))
        self.label_15 = QLabel(self.DMX_tab)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(240, 210, 101, 20))
        self.label_15.setFont(font2)
        self.label_16 = QLabel(self.DMX_tab)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(70, 210, 101, 20))
        self.label_16.setFont(font2)
        self.distination_UID_2 = QLineEdit(self.DMX_tab)
        self.distination_UID_2.setObjectName(u"distination_UID_2")
        self.distination_UID_2.setGeometry(QRect(200, 130, 221, 21))
        sizePolicy.setHeightForWidth(self.distination_UID_2.sizePolicy().hasHeightForWidth())
        self.distination_UID_2.setSizePolicy(sizePolicy)
        self.distination_UID_2.setBaseSize(QSize(0, 0))
        self.distination_UID_2.setFrame(True)
        self.label_17 = QLabel(self.DMX_tab)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(30, 130, 141, 20))
        self.label_17.setFont(font)
        self.label_18 = QLabel(self.DMX_tab)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(60, 250, 101, 20))
        self.label_18.setFont(font2)
        self.spinBox = QSpinBox(self.DMX_tab)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(130, 210, 91, 22))
        self.label_19 = QLabel(self.DMX_tab)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(150, 30, 141, 41))
        self.label_19.setFont(font1)
        self.tabWidget.addTab(self.DMX_tab, "")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 450, 22))
        self.menuAjuda = QMenu(self.menubar)
        self.menuAjuda.setObjectName(u"menuAjuda")
        self.menuSair = QMenu(self.menubar)
        self.menuSair.setObjectName(u"menuSair")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuSair.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionDMX.setText(QCoreApplication.translate("MainWindow", u"RDM", None))
        self.actionRDM.setText(QCoreApplication.translate("MainWindow", u"DMX", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Resposta do slave", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Comando", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Par\u00e2metro", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"0x", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"RDM - Master", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"0x", None))
        self.slave_Response.setText("")
        self.UID_label.setText(QCoreApplication.translate("MainWindow", u"UID de destino", None))
        self.parametro.setItemText(0, QCoreApplication.translate("MainWindow", u"Unique Branch", None))
        self.parametro.setItemText(1, QCoreApplication.translate("MainWindow", u"Mute", None))
        self.parametro.setItemText(2, QCoreApplication.translate("MainWindow", u"Unmute", None))

        self.UID_S_Label.setText(QCoreApplication.translate("MainWindow", u"UID da fonte", None))
        self.Subdevice_label.setText(QCoreApplication.translate("MainWindow", u"Sub device", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"0x", None))
        self.classe.setItemText(0, QCoreApplication.translate("MainWindow", u"DISC", None))
        self.classe.setItemText(1, QCoreApplication.translate("MainWindow", u"GET", None))
        self.classe.setItemText(2, QCoreApplication.translate("MainWindow", u"SET", None))

        self.label_12.setText(QCoreApplication.translate("MainWindow", u"0x", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Classe", None))
        self.send_command.setText(QCoreApplication.translate("MainWindow", u"Enviar comando", None))
        self.Portid_label.setText(QCoreApplication.translate("MainWindow", u"Port ID", None))
        self.destination_UID.setInputMask("")
        self.destination_UID.setText("")
        self.command_1.setText("")
        self.command_2.setText("")
        self.command_4.setText("")
        self.command_3.setText("")
        self.command_6.setText("")
        self.command_8.setText("")
        self.command_7.setText("")
        self.command_5.setText("")
        self.command_14.setText("")
        self.command_10.setText("")
        self.command_16.setText("")
        self.command_12.setText("")
        self.command_15.setText("")
        self.command_11.setText("")
        self.command_13.setText("")
        self.command_9.setText("")
        self.command_20.setText("")
        self.command_18.setText("")
        self.command_19.setText("")
        self.command_17.setText("")
        self.command_26.setText("")
        self.command_31.setText("")
        self.command_32.setText("")
        self.command_29.setText("")
        self.command_37.setText("")
        self.command_30.setText("")
        self.command_22.setText("")
        self.command_36.setText("")
        self.command_28.setText("")
        self.command_24.setText("")
        self.command_27.setText("")
        self.command_23.setText("")
        self.command_25.setText("")
        self.command_21.setText("")
        self.command_34.setText("")
        self.command_33.setText("")
        self.command_35.setText("")
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Comando a ser enviado byte a byte em hexadecimal", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u" 1", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u" 2", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u" 3", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u" 5", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u" 6", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u" 4", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u" 8", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u" 9", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u" 7", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"12", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"14", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"16", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"18", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"17", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"13", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"22", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"23", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"25", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"27", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"29", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"21", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"28", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"26", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"24", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"31", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"32", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"34", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"36", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"38", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"30", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"37", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"35", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"33", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"19", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"20", None))
        self.command_41.setText("")
        self.command_42.setText("")
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"39", None))
        self.command_43.setText("")
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"40", None))
        self.additional_command.setText(QCoreApplication.translate("MainWindow", u"Port ID", None))
        self.label_63.setText(QCoreApplication.translate("MainWindow", u"0x", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RDM_tab), QCoreApplication.translate("MainWindow", u"Mode RDM", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Verde", None))
        self.send_command_2.setText(QCoreApplication.translate("MainWindow", u"Enviar comando", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Azul", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Branco", None))
        self.distination_UID_2.setInputMask("")
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Endere\u00e7o da lumin\u00e1ria", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Vermelho", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"DMX - Master", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DMX_tab), QCoreApplication.translate("MainWindow", u"Mode DMX", None))
        self.menuAjuda.setTitle(QCoreApplication.translate("MainWindow", u"Ajuda", None))
        self.menuSair.setTitle(QCoreApplication.translate("MainWindow", u"Sair", None))
    # retranslateUi

