# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'qt.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFormLayout,
    QGridLayout, QHBoxLayout, QLabel, QLayout,
    QMainWindow, QProgressBar, QPushButton, QSizePolicy,
    QSpinBox, QTextEdit, QVBoxLayout, QWidget)

class Ui_qt(object):
    def setupUi(self, qt):
        if not qt.objectName():
            qt.setObjectName(u"qt")
        qt.resize(1011, 633)
        qt.setCursor(QCursor(Qt.ArrowCursor))
        qt.setWindowOpacity(0.990000000000000)
        self.actionAna_Ekran = QAction(qt)
        self.actionAna_Ekran.setObjectName(u"actionAna_Ekran")
        self.actionHelp = QAction(qt)
        self.actionHelp.setObjectName(u"actionHelp")
        self.centralwidget = QWidget(qt)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayoutWidget = QWidget(self.centralwidget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(220, 90, 781, 521))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.textEdit_3 = QTextEdit(self.gridLayoutWidget)
        self.textEdit_3.setObjectName(u"textEdit_3")

        self.gridLayout.addWidget(self.textEdit_3, 0, 0, 1, 1)

        self.gridLayout.setRowStretch(0, 100)
        self.formLayoutWidget_2 = QWidget(self.centralwidget)
        self.formLayoutWidget_2.setObjectName(u"formLayoutWidget_2")
        self.formLayoutWidget_2.setGeometry(QRect(9, 230, 171, 21))
        self.formLayout_2 = QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setObjectName(u"formLayout_2")
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_4 = QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName(u"label_4")

        self.formLayout_2.setWidget(0, QFormLayout.LabelRole, self.label_4)

        self.label_5 = QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setStyleSheet(u"")

        self.formLayout_2.setWidget(0, QFormLayout.FieldRole, self.label_5)

        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(9, 20, 197, 201))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_10 = QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName(u"label_10")
        font = QFont()
        font.setBold(True)
        self.label_10.setFont(font)

        self.verticalLayout.addWidget(self.label_10)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.label_14 = QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName(u"label_14")

        self.horizontalLayout_3.addWidget(self.label_14)

        self.cb_Port = QComboBox(self.verticalLayoutWidget)
        self.cb_Port.addItem("")
        self.cb_Port.addItem("")
        self.cb_Port.addItem("")
        self.cb_Port.addItem("")
        self.cb_Port.addItem("")
        self.cb_Port.setObjectName(u"cb_Port")
        self.cb_Port.setEditable(True)

        self.horizontalLayout_3.addWidget(self.cb_Port)


        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.label_8 = QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName(u"label_8")

        self.verticalLayout.addWidget(self.label_8)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.pushButton_2 = QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.horizontalLayout_2.addWidget(self.pushButton_2)

        self.pushButton = QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName(u"pushButton")

        self.horizontalLayout_2.addWidget(self.pushButton)


        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.progressBar = QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setValue(24)

        self.verticalLayout.addWidget(self.progressBar)

        self.textEdit = QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setObjectName(u"textEdit")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)

        self.verticalLayout.addWidget(self.textEdit)

        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(880, 50, 121, 41))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(640, 10, 71, 31))
        self.textEdit_2 = QTextEdit(self.centralwidget)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(700, 10, 211, 31))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(910, 10, 91, 31))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(220, 20, 71, 16))
        self.txtIQfile = QTextEdit(self.centralwidget)
        self.txtIQfile.setObjectName(u"txtIQfile")
        self.txtIQfile.setGeometry(QRect(290, 10, 331, 31))
        self.pb_List = QPushButton(self.centralwidget)
        self.pb_List.setObjectName(u"pb_List")
        self.pb_List.setGeometry(QRect(10, 260, 75, 23))
        self.cb_Drive = QComboBox(self.centralwidget)
        self.cb_Drive.addItem("")
        self.cb_Drive.addItem("")
        self.cb_Drive.addItem("")
        self.cb_Drive.setObjectName(u"cb_Drive")
        self.cb_Drive.setGeometry(QRect(140, 260, 41, 20))
        self.cb_Drive.setEditable(True)
        self.pb_Unfre = QPushButton(self.centralwidget)
        self.pb_Unfre.setObjectName(u"pb_Unfre")
        self.pb_Unfre.setGeometry(QRect(100, 290, 81, 23))
        self.pb_Free = QPushButton(self.centralwidget)
        self.pb_Free.setObjectName(u"pb_Free")
        self.pb_Free.setGeometry(QRect(10, 290, 75, 23))
        self.ch_Store = QCheckBox(self.centralwidget)
        self.ch_Store.setObjectName(u"ch_Store")
        self.ch_Store.setGeometry(QRect(10, 330, 70, 17))
        self.ch_Store.setChecked(True)
        self.ch_Copy = QCheckBox(self.centralwidget)
        self.ch_Copy.setObjectName(u"ch_Copy")
        self.ch_Copy.setGeometry(QRect(100, 330, 70, 17))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(12, 0, 71, 16))
        self.label_2.setFont(font)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(90, 0, 111, 20))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(100, 260, 31, 16))
        self.pb_StCo = QPushButton(self.centralwidget)
        self.pb_StCo.setObjectName(u"pb_StCo")
        self.pb_StCo.setGeometry(QRect(50, 450, 121, 31))
        self.sb_Num = QSpinBox(self.centralwidget)
        self.sb_Num.setObjectName(u"sb_Num")
        self.sb_Num.setGeometry(QRect(70, 360, 41, 31))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 370, 71, 16))
        self.ck_Auto = QCheckBox(self.centralwidget)
        self.ck_Auto.setObjectName(u"ck_Auto")
        self.ck_Auto.setGeometry(QRect(10, 400, 111, 17))
        self.ck_Auto.setToolTipDuration(2)
        self.ck_Auto.setChecked(True)
        self.txt_Dir = QTextEdit(self.centralwidget)
        self.txt_Dir.setObjectName(u"txt_Dir")
        self.txt_Dir.setGeometry(QRect(290, 50, 331, 31))
        self.pb_Brow = QPushButton(self.centralwidget)
        self.pb_Brow.setObjectName(u"pb_Brow")
        self.pb_Brow.setGeometry(QRect(620, 50, 91, 31))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(230, 50, 71, 31))
        self.pb_Rena = QPushButton(self.centralwidget)
        self.pb_Rena.setObjectName(u"pb_Rena")
        self.pb_Rena.setGeometry(QRect(730, 50, 91, 31))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(220, 610, 171, 20))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy1)
        self.pb_Clr = QPushButton(self.centralwidget)
        self.pb_Clr.setObjectName(u"pb_Clr")
        self.pb_Clr.setGeometry(QRect(140, 590, 75, 23))
        self.ck_AuSC = QCheckBox(self.centralwidget)
        self.ck_AuSC.setObjectName(u"ck_AuSC")
        self.ck_AuSC.setGeometry(QRect(10, 420, 111, 17))
        self.ck_AuSC.setToolTipDuration(-1)
        self.ck_AuSC.setChecked(False)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(130, 370, 16, 16))
        self.sb_NumFin = QSpinBox(self.centralwidget)
        self.sb_NumFin.setObjectName(u"sb_NumFin")
        self.sb_NumFin.setEnabled(False)
        self.sb_NumFin.setGeometry(QRect(150, 360, 41, 31))
        qt.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.txtIQfile, self.pushButton)
        QWidget.setTabOrder(self.pushButton, self.pb_StCo)
        QWidget.setTabOrder(self.pb_StCo, self.textEdit)
        QWidget.setTabOrder(self.textEdit, self.pushButton_5)
        QWidget.setTabOrder(self.pushButton_5, self.textEdit_2)
        QWidget.setTabOrder(self.textEdit_2, self.pushButton_3)
        QWidget.setTabOrder(self.pushButton_3, self.textEdit_3)
        QWidget.setTabOrder(self.textEdit_3, self.pb_List)
        QWidget.setTabOrder(self.pb_List, self.cb_Drive)
        QWidget.setTabOrder(self.cb_Drive, self.pb_Unfre)
        QWidget.setTabOrder(self.pb_Unfre, self.pb_Free)
        QWidget.setTabOrder(self.pb_Free, self.ch_Store)
        QWidget.setTabOrder(self.ch_Store, self.ch_Copy)
        QWidget.setTabOrder(self.ch_Copy, self.pushButton_2)
        QWidget.setTabOrder(self.pushButton_2, self.sb_Num)
        QWidget.setTabOrder(self.sb_Num, self.ck_Auto)
        QWidget.setTabOrder(self.ck_Auto, self.txt_Dir)
        QWidget.setTabOrder(self.txt_Dir, self.pb_Brow)
        QWidget.setTabOrder(self.pb_Brow, self.pb_Rena)

        self.retranslateUi(qt)

        QMetaObject.connectSlotsByName(qt)
    # setupUi

    def retranslateUi(self, qt):
        qt.setWindowTitle(QCoreApplication.translate("qt", u"BIRL - Zonare COM Tool V1.0", None))
#if QT_CONFIG(statustip)
        qt.setStatusTip(QCoreApplication.translate("qt", u"Mehmet Cagri Aksoy 2018-2022", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        qt.setWhatsThis(QCoreApplication.translate("qt", u"Serial Communication Program Mehmet Cagri Aksoy 2018-2022", None))
#endif // QT_CONFIG(whatsthis)
        self.actionAna_Ekran.setText(QCoreApplication.translate("qt", u"Ana Ekran", None))
        self.actionHelp.setText(QCoreApplication.translate("qt", u"Help", None))
        self.label_4.setText(QCoreApplication.translate("qt", u"Port Status", None))
        self.label_5.setText(QCoreApplication.translate("qt", u"Not Connected", None))
        self.label_10.setText(QCoreApplication.translate("qt", u"Connection Options:", None))
        self.label_14.setText(QCoreApplication.translate("qt", u"Select Port:", None))
        self.cb_Port.setItemText(0, QCoreApplication.translate("qt", u"COM1", None))
        self.cb_Port.setItemText(1, QCoreApplication.translate("qt", u"COM2", None))
        self.cb_Port.setItemText(2, QCoreApplication.translate("qt", u"COM3", None))
        self.cb_Port.setItemText(3, QCoreApplication.translate("qt", u"COM4", None))
        self.cb_Port.setItemText(4, QCoreApplication.translate("qt", u"COM5", None))

        self.cb_Port.setCurrentText(QCoreApplication.translate("qt", u"COM1", None))
        self.label_8.setText(QCoreApplication.translate("qt", u"Connection Percentage Status:", None))
        self.pushButton_2.setText(QCoreApplication.translate("qt", u"STOP", None))
        self.pushButton.setText(QCoreApplication.translate("qt", u"START", None))
        self.pushButton_5.setText(QCoreApplication.translate("qt", u"Save Log as .txt", None))
        self.label_9.setText(QCoreApplication.translate("qt", u"Send Cmd:", None))
        self.pushButton_3.setText(QCoreApplication.translate("qt", u"SEND", None))
        self.label.setText(QCoreApplication.translate("qt", u"IQ File Name:", None))
        self.pb_List.setText(QCoreApplication.translate("qt", u"List Drive", None))
        self.cb_Drive.setItemText(0, QCoreApplication.translate("qt", u"J:", None))
        self.cb_Drive.setItemText(1, QCoreApplication.translate("qt", u"F:", None))
        self.cb_Drive.setItemText(2, QCoreApplication.translate("qt", u"G:", None))

        self.cb_Drive.setCurrentText(QCoreApplication.translate("qt", u"J:", None))
        self.pb_Unfre.setText(QCoreApplication.translate("qt", u"Cine Unfreeze", None))
        self.pb_Free.setText(QCoreApplication.translate("qt", u"Cine Freeze", None))
        self.ch_Store.setText(QCoreApplication.translate("qt", u"Store Data", None))
        self.ch_Copy.setText(QCoreApplication.translate("qt", u"Copy Data", None))
        self.label_2.setText(QCoreApplication.translate("qt", u"PORT Name:", None))
        self.label_11.setText(QCoreApplication.translate("qt", u"-", None))
        self.label_6.setText(QCoreApplication.translate("qt", u"Drive:", None))
        self.pb_StCo.setText(QCoreApplication.translate("qt", u"Store/Copy", None))
        self.label_7.setText(QCoreApplication.translate("qt", u"File Number:", None))
#if QT_CONFIG(tooltip)
        self.ck_Auto.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.ck_Auto.setText(QCoreApplication.translate("qt", u"Auto increment", None))
        self.pb_Brow.setText(QCoreApplication.translate("qt", u"Browse...", None))
        self.label_12.setText(QCoreApplication.translate("qt", u"Directory:", None))
        self.pb_Rena.setText(QCoreApplication.translate("qt", u"Rename Files", None))
        self.label_3.setText(QCoreApplication.translate("qt", u"Gathering / Sending Data (Rx/Tx)", None))
        self.pb_Clr.setText(QCoreApplication.translate("qt", u"Clear Screen", None))
#if QT_CONFIG(tooltip)
        self.ck_AuSC.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.ck_AuSC.setText(QCoreApplication.translate("qt", u"Auto Store/Copy", None))
        self.label_13.setText(QCoreApplication.translate("qt", u"Fin:", None))
    # retranslateUi

